spring:
  application:
    name: spring-cloud-service
  main:
    banner:
      mode: off
  datasource:
    name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/exam?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 799521
    type: com.alibaba.druid.pool.DruidDataSource
  resources:
    static-locations: classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/
  mvc:
    date-format: yyyy-MM-dd hh:mm:ss
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
logging:
  level:
    com:
      aaa:
        mapper: debug
mybatis:
  type-aliases-package: com.aaa.entity
#pagehelper 分页
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  pageSizeZero: true
  params: countSql
