#pagehelper 分页
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  pageSizeZero: true
  params: countSql
spring:
  application:
    name: spring-cloud-web
  main:
    banner:
      mode: off
  resources:
    static-locations: classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/
#    mvc:
#      date-format: yyyy-MM-dd hh:mm:ss
  thymeleaf:
    cache: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true