spring:
  application:
    name: spring-cloud-zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
zuul:
  routes:
    api-a:
      path: /api/a/**
      serviceId: spring-cloud-web
#    api-b:
#      path: /api/b/**
#      serviceId: spring-cloud-web2